# Generated by Django 4.0.1 on 2022-01-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheludi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('worked', models.BooleanField(default=True, verbose_name='Работает/Уволен')),
                ('order', models.CharField(max_length=250, verbose_name='Приказ ввода вывода с удаленки')),
                ('MOL', models.BooleanField(default=False)),
                ('cabinet', models.CharField(max_length=100, verbose_name='Кабинет')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование отдела')),
                ('address', models.TextField(verbose_name='Адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Technics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('serynic', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('inventarnic', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('state', models.CharField(choices=[('Введен в эксплуатацию', 'Введен в эксплуатацию'), ('Принят к учету', 'Принят к учету')], default='Введен в эксплуатацию', max_length=100, verbose_name='Состояние')),
                ('price', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('сommissioning_date', models.DateTimeField(verbose_name='Дата ввода в эксплуатацию')),
                ('FIO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='chelud', to='index.cheludi')),
                ('MOL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='mol', to='index.cheludi')),
            ],
        ),
        migrations.AddField(
            model_name='cheludi',
            name='otdel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.departments'),
        ),
    ]
