# Generated by Django 4.0.1 on 2022-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Балансовая стоимость'),
        ),
        migrations.AlterField(
            model_name='technics',
            name='сommissioning_date',
            field=models.DateField(verbose_name='Дата ввода в эксплуатацию'),
        ),
    ]
