# Generated by Django 4.0.1 on 2022-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='ValueAttribute',
        ),
    ]
